@startuml
skinparam shadowing false
actor       Пользователь  as  P1
participant Интерфейс as Inf
participant "Система учета бронирования" as BR
participant "База данных" as BD
participant "Платежная система" as PS

P1 -> Inf : Открытие меню брони автомобилей
Inf -> BR : Запрос списка автомобилей
BR -> BD : Запрос занятых автомобилей
BR <- BD : Вывод списка заняты\nавтомобилей и даты освобождения
Inf <- BR : Вывод доступных\nи даты освобождения\nзанятых автомобилей


P1 <- Inf : Отображение перечня автомобилей
P1 -> Inf : Добавление автомобиля в корзину
Inf -> BR : Добавление автомобиля в корзину

P1 -> Inf : Переход к бронированию
Inf -> BR : Запрос списка доступных адресов\nдля забора автомобиля
Inf <- BR : Вывод доступных\nадресов

P1 <- Inf : Отображение доступных адресов
P1 -> Inf : Выбор адреса забора автомобиля\nи подтверждение заказа

Inf -> BR : Бронирование автомобиля
BR -> BD : Создание заказа
BR <- BD : Подтверждение создания заказа
Inf <- BR : Выставление счета на оплату
P1 <- Inf : Переход на страницу оплаты
P1 -> Inf : Ввод реквизитов банковской карты

Inf -> PS : Проведение платежа по введенным реквизитам

PS -> PS : Проведение платежа

PS -> BR : Изменение статуса оплаты

BR -> BD : Изменение статуса заказа
BR <- BD : Подтверждение изменения статуса заказа
Inf <- BR : Подтверждение изменения\nстатус заказа
P1 <- Inf : Отображение успешной оплаты


@enduml